# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ryan Spencer
tagline:          Tall, dark, and codesome
url:              http://rjspencer.github.io
paginate:         3
baseurl:          /
author:
  name:           Ryan Spencer
  url:            https://twitter.com/rjspencer
  email:          rjspencer82@gmail.com

# Custom vars
version:          2.0.0
github:
  repo:           https://github.com/rjspencer/rjspencer.github.io

# Navigation
pages_list:
  Resume: '/'
