# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ryan Spencer
tagline:          Tall, dark, and codesome
url:              http://rjspencer.github.io
paginate:         1
baseurl:          /
author:
  name:           Ryan Spencer
  url:            https://twitter.com/rjspencer
  email:          rjspencer82@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/rjspencer/rjspencer.github.io
